### ISSUE TITLE
Custom DataTable

### ISSUE THREAD

**Issue by IHesamI** [app-generator/django-dynamic-datatb#8]
I think it is better to have a custom data table and not use bootstrap or simple-datatables
So, I implemented an initial table if you like it, inform me to complete it.

**Comment by app-generator** [comment]
hello @IHesamI 
a custom table is a great idea. 
the goal is to refactor the layout to make it `plain vanilla` usable in many contexts (BS4, BS5, tailwind)

Please proceed with this. Ty!

**Comment by app-generator** [comment]
P.S. just release the latest changes. here is the UI: 

![image](https://user-images.githubusercontent.com/51070104/223216118-a0fb6345-eb64-4169-bc9f-da53eb95e70e.png)

**Comment by IHesamI** [comment]
I have not removed the previous Data Table now it  should be Ok.

**Comment by app-generator** [comment]
Hello @IHesamI 
Ty for your work. 

Here is an issue visible in the latest version:

When the model contains more than 1 field, the popup always shows only ID + name, which seems hard coded. 

Please take a look. Ty! 

---

> My current model is this:

```python
class Product(models.Model):
    id     = models.AutoField(primary_key=True)
    info3  = models.CharField(max_length = 100, default = '')
    info4  = models.CharField(max_length = 100, default = '')
```

---

> The UI -> **OK**

![image](https://user-images.githubusercontent.com/51070104/223523335-f9930e78-5cc3-4a0a-9631-5d009ae06cf8.png)

---

> The `Add Item` Popup -> **NOT Ok**

Please note that the popup doesn't have any "NAME" field. 

![image](https://user-images.githubusercontent.com/51070104/223523512-de71d808-94a8-445f-8f8e-42b398c88e35.png)

**Comment by IHesamI** [comment]
Oh, I will fix that. 
Ty for your response.

**Comment by app-generator** [comment]
Guys, I know that this task is pure hell, but .. somehow, we need to fix it and move forward. 
I will actively involve in the code, so if someone hits a dead end, just ask for help.
Until the task ends, we are a team. 
🚀🚀

**Comment by IHesamI** [comment]
I think the problem is solved

> Hello @IHesamI Ty for your work.
> 
> Here is an issue visible in the latest version:
> 
> When the model contains more than 1 field, the popup always shows only ID + name, which seems hard coded.
> 
> Please take a look. Ty!
> 
> > My current model is this:
> 
> ```python
> class Product(models.Model):
>     id     = models.AutoField(primary_key=True)
>     info3  = models.CharField(max_length = 100, default = '')
>     info4  = models.CharField(max_length = 100, default = '')
> ```
> 
> > The UI -> **OK**
> 
> ![image](https://user-images.githubusercontent.com/51070104/223523335-f9930e78-5cc3-4a0a-9631-5d009ae06cf8.png)
> 
> > The `Add Item` Popup -> **NOT Ok**
> 
> Please note that the popup doesn't have any "NAME" field.
> 
> ![image](https://user-images.githubusercontent.com/51070104/223523512-de71d808-94a8-445f-8f8e-42b398c88e35.png)

**Comment by app-generator** [comment]
Hello @IHesamI 

Ty for the latest fixes. 

We are getting closer. Please update, I did some small changes to align edit icons to the right. 
A minor issue is the alignment of export icons that look pulled to the left (not centered). 

Please take a look. Ty! 

![image](https://user-images.githubusercontent.com/51070104/223631222-bfa6c113-3442-45f0-9e2c-5aaae01ba843.png)

**Comment by IHesamI** [comment]
I've added a few styles to fixed alignment.
And when I test new Data Table with more than one Table in a page it does not work properly, I fixed it but please you test it if there is any issue left.

**Comment by app-generator** [comment]
Hello @IHesamI 
I will test and get back. 
ty!

**Comment by IHesamI** [comment]
I added more styles  and fixed some bugs.

**Comment by app-generator** [comment]
Ty @IHesamI 
Let me test it ..

**Comment by app-generator** [comment]
Hello @IHesamI 
Looks good. 

Can you confirm that `server-side` pagination is still there? 
Changing the page is suspectly fast. 

Ty!

**Comment by IHesamI** [comment]
Sure, this is the method which handles the pagination 
![Capture](https://user-images.githubusercontent.com/81189508/223905573-d03332bb-b892-46ff-92eb-65936fac096c.PNG)
I think It is fast because nothing complex happened here.
You can also check the server logs.

**Comment by app-generator** [comment]
Perfect. Ty @IHesamI

**Comment by IHesamI** [comment]
Hello @app-generator 
I created a fork of the project to run some tests and evalute capabilities of the Tables.

**Comment by app-generator** [comment]
Hello @IHesamI 
Thank you! 

That's something we can use for the next embedded library: `dynamic charts`. 
Let us know if you spot some issues during tests. 

🚀🚀

**Comment by IHesamI** [comment]
Hello @app-generator 
These are my concerns.
1- DateFields, I use a Datefield in a model and when i render this model the is_date parameter return false for this field.
2- Realations, when there is a relation between models the related fields are not in Heading parameter.
3- Cleaning, I think we should delete some files as they are not useful anymore.
4- Readme, as we changed the UI and customize the DataTable it is better to update the Readme file.

**Comment by app-generator** [comment]
Hello @IHesamI 
Thank you for the follow-up.  Here are my answers: 

- The `datetime` field was working in the past,  this is clearly a regression that needs to be fixed 
- Relations are not supported for the moment. This use case needs special attention and is not a PRIO in this sprint
- Cleaning .. for sure needs to be done. Please proceed. 
- README is up2date, thanks for the reminder. 

Let us know if you need help with some item. 
Thanks again for your work.

**Comment by IHesamI** [comment]
Thank you for response @app-generator 
I deleted some files and Cleaned the Codebase.

**Comment by app-generator** [comment]
someone is really fast ... 🚀🚀

**Comment by app-generator** [comment]
Closing
